### PR TITLE
Cleaned up README a bit

### PR DESCRIPTION
**Pull request by hikarutilmitt**
fixed some typos
clarified the firmware update process
removed empty notations
provided as link to the firmware as well as the file description

### CODE REVIEW

**Comment by 3tilley** [comment]
This picks up everything I'd noticed. Is is worth putting the notes inside italics or other demarcation? It's a bit tricky difficult to follow the flow

1. Blah
2. Bar
Note A: Don't forget foo
4. Baz

vs

1. Blah
2. Bar
_Note A: Don't forget foo_
3. Baz

**Comment by hikarutilmitt** [comment]
I was wrestling with either that or maybe just rolling the notes into their actual steps

**Comment by 3tilley** [comment]
I'm torn, I really really liked the notes once I understood the process a bit better, but they did get in the way a little while I was just trying to work it out.

It reads a lot more nicely now, but some of the gold dust from experienced JLCPCB orderers has been lost. Maybe appendix? Or it can be added at a later date

**Review by TheTrainGoes — APPROVED** [review]

**Comment by TheTrainGoes** [comment]
Hey @hikarutilmitt apologies I missed this.  

I would like to keep some of the failure rate stats if possible.

**Review by TheTrainGoes — APPROVED** [review]

**Review by arntsonl — APPROVED** [review]
Nice, good cleanup!

**Pull request closed without merging**
